### ISSUE TITLE
[Todo] Add user-friendly documentation

### ISSUE THREAD

**Issue by Alexenon** [Alexenon/ExpenseTracker#85]
Documentation should contain

- [ ] How to run, which port is the application
- [ ] Information about setting up required OS system variables 
- [ ] Database required scripts
- [ ] Required applications
- [ ] How to use API
